"use client";

import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import QRCode from "qrcode";
import { useSettings } from "@/context/SettingsContext";
import { useToast } from "@/context/ToastContext";
import { getReport, updateReport } from "@/lib/storage";
import { CallReport } from "@/lib/types";
import { categoryLabels, localeFor } from "@/lib/i18n";
import { TranscriptView } from "@/components/TranscriptView";
import { ExplainabilityPanel } from "@/components/ExplainabilityPanel";
import { CheckIcon, KeyIcon } from "@/components/icons";

const bandColor = {
  safe: "var(--trust-safe)",
  caution: "var(--trust-caution)",
  danger: "var(--trust-danger)",
} as const;

const bandLabel = {
  en: { safe: "Looks safe", caution: "Stay alert", danger: "High risk detected" },
  es: { safe: "Parece seguro", caution: "Mantente alerta", danger: "Riesgo alto detectado" },
} as const;

function sparklinePath(values: number[], width: number, height: number) {
  if (values.length === 0) return "";
  const max = 100;
  const step = width / Math.max(1, values.length - 1);
  return values
    .map((v, i) => `${i === 0 ? "M" : "L"} ${(i * step).toFixed(1)} ${(height - (v / max) * height).toFixed(1)}`)
    .join(" ");
}

function downloadFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildFtcStyleReport(report: CallReport, lang: "en" | "es"): string {
  const lines: string[] = [];
  lines.push(lang === "en" ? "SUSPECTED SCAM CALL — INCIDENT SUMMARY" : "LLAMADA SOSPECHOSA DE ESTAFA — RESUMEN DEL INCIDENTE");
  lines.push(lang === "en" ? "Generated by Guardian Line" : "Generado por Guardian Line");
  lines.push("");
  lines.push(`${lang === "en" ? "Date/time" : "Fecha/hora"}: ${new Date(report.startedAt).toLocaleString()}`);
  lines.push(`${lang === "en" ? "Duration" : "Duración"}: ${Math.round(report.durationMs / 1000)}s`);
  lines.push(`${lang === "en" ? "Scenario" : "Escenario"}: ${report.scenario}`);
  lines.push(`${lang === "en" ? "Overall verdict" : "Veredicto general"}: ${bandLabel[lang][report.finalBand]} (${report.finalTrustScore}/100 trust)`);
  if (report.safeWordChallenged) {
    lines.push(
      `${lang === "en" ? "Safe word check" : "Verificación de palabra segura"}: ${
        report.safeWordPassed
          ? lang === "en" ? "Passed" : "Aprobada"
          : lang === "en" ? "Failed / not given" : "Fallida / no proporcionada"
      }`
    );
  }
  lines.push("");
  lines.push(lang === "en" ? "FLAGGED MOMENTS:" : "MOMENTOS MARCADOS:");
  report.flags
    .sort((a, b) => a.timestampMs - b.timestampMs)
    .forEach((f) => {
      const t = Math.floor(f.timestampMs / 1000);
      lines.push(`  [${Math.floor(t / 60)}:${(t % 60).toString().padStart(2, "0")}] ${categoryLabels[f.category][lang]} — ${f.message}`);
    });
  lines.push("");
  lines.push(lang === "en" ? "FULL TRANSCRIPT:" : "TRANSCRIPCIÓN COMPLETA:");
  report.transcript.forEach((entry) => {
    const t = Math.floor(entry.timestampMs / 1000);
    const speakerLabel = entry.speaker === "caller" ? (lang === "en" ? "Caller" : "Quien llama") : lang === "en" ? "You" : "Tú";
    lines.push(`  [${Math.floor(t / 60)}:${(t % 60).toString().padStart(2, "0")}] ${speakerLabel}: ${entry.text}`);
  });
  lines.push("");
  lines.push(
    lang === "en"
      ? "This summary was generated automatically and is intended to support — not replace — a report filed with the FTC (reportfraud.ftc.gov) or your financial institution's fraud department."
      : "Este resumen se generó automáticamente y busca apoyar — no reemplazar — una denuncia ante la FTC (reportfraud.ftc.gov) o el departamento de fraude de su institución financiera."
  );
  return lines.join("\n");
}

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>();
  const { settings, strings } = useSettings();
  const { showToast } = useToast();
  const lang = settings.language;
  const [report, setReport] = useState<CallReport | null | undefined>(undefined);

  useEffect(() => {
    // localStorage is only available client-side, so this can't be a
    // lazy useState initializer without causing a hydration mismatch.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setReport(getReport(params.id));
  }, [params.id]);

  if (report === undefined) return null;

  if (!report) {
    return (
      <div className="mx-auto w-full max-w-3xl flex-1 px-5 py-16 text-center">
        <p className="text-foreground-muted">
          {lang === "en" ? "Report not found on this device." : "Informe no encontrado en este dispositivo."}
        </p>
        <Link href="/reports" className="mt-4 inline-block text-accent underline">
          {strings.nav.reports}
        </Link>
      </div>
    );
  }

  const trustValues = report.trustHistory.map((h) => h.trustScore);
  const color = bandColor[report.finalBand];

  return <ReportBody report={report} lang={lang} strings={strings} showToast={showToast} trustValues={trustValues} color={color} />;
}

function ReportBody({
  report,
  lang,
  strings,
  showToast,
  trustValues,
  color,
}: {
  report: CallReport;
  lang: "en" | "es";
  strings: ReturnType<typeof import("@/lib/i18n").t>;
  showToast: (message: string, variant?: "default" | "success" | "danger") => void;
  trustValues: number[];
  color: string;
}) {
  const pathRef = useRef<SVGPathElement>(null);

  useEffect(() => {
    const el = pathRef.current;
    if (!el) return;
    const length = el.getTotalLength();
    el.style.strokeDasharray = `${length}`;
    el.style.strokeDashoffset = `${length}`;
    el.getBoundingClientRect(); // force reflow so the transition actually plays
    el.style.transition = "stroke-dashoffset 1.1s cubic-bezier(0.22, 1, 0.36, 1)";
    el.style.strokeDashoffset = "0";
  }, [trustValues.length]);

  const [tags, setTags] = useState(report.tags);
  const [tagInput, setTagInput] = useState("");
  const [notes, setNotes] = useState(report.notes);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);

  useEffect(() => {
    const shortSummary = `Guardian Line — ${report.scenario} — ${bandLabel[lang][report.finalBand]} (${report.finalTrustScore}/100) — ${new Date(report.startedAt).toLocaleDateString()}`;
    QRCode.toDataURL(shortSummary, { width: 160, margin: 1, color: { dark: "#0a0e1a", light: "#ffffff" } })
      .then(setQrDataUrl)
      .catch(() => setQrDataUrl(null));
  }, [report, lang]);

  function addTag() {
    const t = tagInput.trim();
    if (!t || tags.includes(t)) return;
    const next = [...tags, t];
    setTags(next);
    updateReport(report.id, { tags: next });
    setTagInput("");
  }

  function removeTag(t: string) {
    const next = tags.filter((x) => x !== t);
    setTags(next);
    updateReport(report.id, { tags: next });
  }

  function saveNotes(value: string) {
    setNotes(value);
    updateReport(report.id, { notes: value });
  }

  const [feedback, setFeedback] = useState(report.feedback);
  function giveFeedback(value: "helpful" | "not-helpful") {
    const next = feedback === value ? null : value;
    setFeedback(next);
    updateReport(report.id, { feedback: next });
    showToast(
      next
        ? lang === "en"
          ? "Thanks — this helps tune future sensitivity"
          : "Gracias — esto ayuda a ajustar la sensibilidad"
        : lang === "en"
        ? "Feedback removed"
        : "Comentario eliminado"
    );
  }

  return (
    <div className="mx-auto w-full max-w-4xl flex-1 px-5 py-10 print:max-w-full">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="text-xs uppercase tracking-wide text-foreground-muted">{strings.report.title}</div>
          <h1 className="mt-1 text-2xl font-semibold tracking-tight">{report.scenario}</h1>
          <div className="mt-1 text-sm text-foreground-muted">
            {new Date(report.startedAt).toLocaleString(localeFor(lang))} ·{" "}
            {Math.round(report.durationMs / 1000)}s
          </div>
        </div>
        <div className="flex flex-wrap gap-2 print:hidden">
          <button
            onClick={async () => {
              try {
                await navigator.clipboard.writeText(buildFtcStyleReport(report, lang));
                showToast(lang === "en" ? "Summary copied to clipboard" : "Resumen copiado al portapapeles", "success");
              } catch {
                showToast(lang === "en" ? "Couldn't copy — try the download instead" : "No se pudo copiar — intenta la descarga", "danger");
              }
            }}
            className="btn-press rounded-full border border-border-strong px-4 py-2 text-xs font-medium hover:bg-background-elevated"
          >
            {lang === "en" ? "Copy summary" : "Copiar resumen"}
          </button>
          <button
            onClick={() => window.print()}
            className="btn-press rounded-full border border-border-strong px-4 py-2 text-xs font-medium hover:bg-background-elevated"
          >
            {strings.report.export}
          </button>
          {typeof navigator !== "undefined" && "share" in navigator && (
            <button
              onClick={async () => {
                try {
                  await navigator.share({
                    title: lang === "en" ? "Guardian Line call summary" : "Resumen de llamada de Guardian Line",
                    text: buildFtcStyleReport(report, lang),
                  });
                } catch {
                  // user cancelled the native share sheet — nothing to do
                }
              }}
              className="btn-press rounded-full border border-border-strong px-4 py-2 text-xs font-medium hover:bg-background-elevated"
            >
              {lang === "en" ? "Share…" : "Compartir…"}
            </button>
          )}
          <button
            onClick={() => {
              downloadFile(`guardian-line-report-${report.id}.txt`, buildFtcStyleReport(report, lang));
              showToast(lang === "en" ? "Report downloaded" : "Informe descargado", "success");
            }}
            className="btn-press rounded-full bg-accent-solid px-4 py-2 text-xs font-medium text-white hover:bg-accent-solid-hover"
          >
            {strings.report.fileScam}
          </button>
        </div>
      </div>

      <div className="card-hover animate-fade-in-up mt-8 grid grid-cols-1 sm:grid-cols-[auto_1fr] gap-6 rounded-2xl border border-border-subtle bg-background-card p-6">
        <div className="relative flex flex-col items-center justify-center">
          {report.finalBand === "safe" && (
            <div
              className="animate-celebrate-glow pointer-events-none absolute inset-0 rounded-full"
              style={{ boxShadow: `0 0 40px 10px color-mix(in srgb, ${color} 35%, transparent)` }}
            />
          )}
          <div className="animate-settle-bounce text-4xl font-bold tabular-nums" style={{ color }}>
            {report.finalTrustScore}
          </div>
          <div
            className="mt-2 rounded-full px-3 py-1 text-xs font-semibold"
            style={{ color, backgroundColor: `color-mix(in srgb, ${color} 16%, transparent)` }}
          >
            {bandLabel[lang][report.finalBand]}
          </div>
        </div>
        <div>
          <div className="text-xs text-foreground-muted mb-2">
            {lang === "en" ? "Trust score over time" : "Puntuación de confianza en el tiempo"}
          </div>
          {trustValues.length > 1 ? (
            <svg viewBox="0 0 300 60" className="w-full h-16" preserveAspectRatio="none">
              <path ref={pathRef} d={sparklinePath(trustValues, 300, 60)} fill="none" stroke={color} strokeWidth={2} />
            </svg>
          ) : (
            <div className="text-xs text-foreground-muted">
              {lang === "en" ? "Not enough data captured." : "No se capturaron suficientes datos."}
            </div>
          )}
          {report.safeWordChallenged && (
            <div className="mt-3 flex items-center gap-2 text-xs">
              <KeyIcon className="h-4 w-4 text-accent" />
              {report.safeWordPassed ? (
                <span className="text-trust-safe flex items-center gap-1">
                  <CheckIcon className="h-3.5 w-3.5" /> {strings.safeWord.passed}
                </span>
              ) : (
                <span className="text-trust-danger">{strings.safeWord.failed}</span>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="card-hover animate-fade-in-up mt-6 grid grid-cols-1 sm:grid-cols-[1fr_auto] gap-6 rounded-2xl border border-border-subtle bg-background-card p-6 print:hidden">
        <div className="space-y-4">
          <div>
            <div className="mb-2 text-xs font-semibold text-foreground-muted">{lang === "en" ? "Tags" : "Etiquetas"}</div>
            <div className="flex flex-wrap items-center gap-2">
              {tags.map((t) => (
                <span key={t} className="flex items-center gap-1 rounded-full bg-background-elevated px-2.5 py-1 text-xs">
                  {t}
                  <button onClick={() => removeTag(t)} className="text-foreground-muted hover:text-trust-danger">
                    ×
                  </button>
                </span>
              ))}
              <input
                value={tagInput}
                onChange={(e) => setTagInput(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && addTag()}
                placeholder={lang === "en" ? "Add a tag…" : "Añadir etiqueta…"}
                className="w-32 rounded-full border border-border-subtle bg-background-elevated px-2.5 py-1 text-xs outline-none focus:border-accent"
              />
            </div>
          </div>
          <div>
            <div className="mb-2 text-xs font-semibold text-foreground-muted">{lang === "en" ? "Notes" : "Notas"}</div>
            <textarea
              value={notes}
              onChange={(e) => saveNotes(e.target.value)}
              placeholder={lang === "en" ? "Any context worth remembering about this call…" : "Cualquier contexto que valga la pena recordar…"}
              rows={2}
              className="w-full rounded-lg border border-border-subtle bg-background-elevated px-3 py-2 text-xs outline-none focus:border-accent"
            />
          </div>
          <div>
            <div className="mb-2 text-xs font-semibold text-foreground-muted">
              {lang === "en" ? "Was this assessment helpful?" : "¿Fue útil esta evaluación?"}
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => giveFeedback("helpful")}
                aria-pressed={feedback === "helpful"}
                className={`btn-press rounded-full border px-3 py-1.5 text-xs font-medium ${
                  feedback === "helpful"
                    ? "border-trust-safe bg-trust-safe/15 text-trust-safe"
                    : "border-border-subtle hover:bg-background-elevated"
                }`}
              >
                👍 {lang === "en" ? "Helpful" : "Útil"}
              </button>
              <button
                onClick={() => giveFeedback("not-helpful")}
                aria-pressed={feedback === "not-helpful"}
                className={`btn-press rounded-full border px-3 py-1.5 text-xs font-medium ${
                  feedback === "not-helpful"
                    ? "border-trust-danger bg-trust-danger/15 text-trust-danger"
                    : "border-border-subtle hover:bg-background-elevated"
                }`}
              >
                👎 {lang === "en" ? "Not helpful" : "No útil"}
              </button>
            </div>
          </div>
        </div>
        {qrDataUrl && (
          <div className="flex flex-col items-center justify-center gap-1">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={qrDataUrl} alt="QR code summary" className="rounded-lg" width={110} height={110} />
            <span className="text-center text-[10px] text-foreground-muted">
              {lang === "en" ? "Scan for a short summary" : "Escanea para un resumen breve"}
            </span>
          </div>
        )}
      </div>

      <div className="mt-6 grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="card-hover animate-fade-in-up rounded-2xl border border-border-subtle bg-background-card p-5 h-[420px]" style={{ animationDelay: "80ms" }}>
          <h2 className="mb-3 text-sm font-semibold text-foreground-muted">
            {lang === "en" ? "Full transcript" : "Transcripción completa"}
          </h2>
          <div className="h-[calc(100%-2rem)]">
            <TranscriptView entries={report.transcript} />
          </div>
        </div>
        <div className="card-hover animate-fade-in-up rounded-2xl border border-border-subtle bg-background-card p-5 h-[420px]" style={{ animationDelay: "140ms" }}>
          <h2 className="mb-3 text-sm font-semibold text-foreground-muted">
            {lang === "en" ? "Flagged moments" : "Momentos marcados"}
          </h2>
          <div className="h-[calc(100%-2rem)]">
            <ExplainabilityPanel flags={report.flags} />
          </div>
        </div>
      </div>
    </div>
  );
}
