"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useSettings } from "@/context/SettingsContext";
import { useToast } from "@/context/ToastContext";
import { getReport } from "@/lib/storage";
import { CallReport } from "@/lib/types";
import { categoryLabels } from "@/lib/i18n";
import { TranscriptView } from "@/components/TranscriptView";
import { ExplainabilityPanel } from "@/components/ExplainabilityPanel";
import { CheckIcon, KeyIcon } from "@/components/icons";

const bandColor = {
  safe: "var(--trust-safe)",
  caution: "var(--trust-caution)",
  danger: "var(--trust-danger)",
} as const;

const bandLabel = {
  en: { safe: "Looks safe", caution: "Stay alert", danger: "High risk detected" },
  es: { safe: "Parece seguro", caution: "Mantente alerta", danger: "Riesgo alto detectado" },
} as const;

function sparklinePath(values: number[], width: number, height: number) {
  if (values.length === 0) return "";
  const max = 100;
  const step = width / Math.max(1, values.length - 1);
  return values
    .map((v, i) => `${i === 0 ? "M" : "L"} ${(i * step).toFixed(1)} ${(height - (v / max) * height).toFixed(1)}`)
    .join(" ");
}

function downloadFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildFtcStyleReport(report: CallReport, lang: "en" | "es"): string {
  const lines: string[] = [];
  lines.push(lang === "en" ? "SUSPECTED SCAM CALL — INCIDENT SUMMARY" : "LLAMADA SOSPECHOSA DE ESTAFA — RESUMEN DEL INCIDENTE");
  lines.push(lang === "en" ? "Generated by Guardian Line" : "Generado por Guardian Line");
  lines.push("");
  lines.push(`${lang === "en" ? "Date/time" : "Fecha/hora"}: ${new Date(report.startedAt).toLocaleString()}`);
  lines.push(`${lang === "en" ? "Duration" : "Duración"}: ${Math.round(report.durationMs / 1000)}s`);
  lines.push(`${lang === "en" ? "Scenario" : "Escenario"}: ${report.scenario}`);
  lines.push(`${lang === "en" ? "Overall verdict" : "Veredicto general"}: ${bandLabel[lang][report.finalBand]} (${report.finalTrustScore}/100 trust)`);
  if (report.safeWordChallenged) {
    lines.push(
      `${lang === "en" ? "Safe word check" : "Verificación de palabra segura"}: ${
        report.safeWordPassed
          ? lang === "en" ? "Passed" : "Aprobada"
          : lang === "en" ? "Failed / not given" : "Fallida / no proporcionada"
      }`
    );
  }
  lines.push("");
  lines.push(lang === "en" ? "FLAGGED MOMENTS:" : "MOMENTOS MARCADOS:");
  report.flags
    .sort((a, b) => a.timestampMs - b.timestampMs)
    .forEach((f) => {
      const t = Math.floor(f.timestampMs / 1000);
      lines.push(`  [${Math.floor(t / 60)}:${(t % 60).toString().padStart(2, "0")}] ${categoryLabels[f.category][lang]} — ${f.message}`);
    });
  lines.push("");
  lines.push(lang === "en" ? "FULL TRANSCRIPT:" : "TRANSCRIPCIÓN COMPLETA:");
  report.transcript.forEach((entry) => {
    const t = Math.floor(entry.timestampMs / 1000);
    const speakerLabel = entry.speaker === "caller" ? (lang === "en" ? "Caller" : "Quien llama") : lang === "en" ? "You" : "Tú";
    lines.push(`  [${Math.floor(t / 60)}:${(t % 60).toString().padStart(2, "0")}] ${speakerLabel}: ${entry.text}`);
  });
  lines.push("");
  lines.push(
    lang === "en"
      ? "This summary was generated automatically and is intended to support — not replace — a report filed with the FTC (reportfraud.ftc.gov) or your financial institution's fraud department."
      : "Este resumen se generó automáticamente y busca apoyar — no reemplazar — una denuncia ante la FTC (reportfraud.ftc.gov) o el departamento de fraude de su institución financiera."
  );
  return lines.join("\n");
}

export default function ReportDetailPage() {
  const params = useParams<{ id: string }>();
  const { settings, strings } = useSettings();
  const { showToast } = useToast();
  const lang = settings.language;
  const [report, setReport] = useState<CallReport | null | undefined>(undefined);

  useEffect(() => {
    // localStorage is only available client-side, so this can't be a
    // lazy useState initializer without causing a hydration mismatch.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setReport(getReport(params.id));
  }, [params.id]);

  if (report === undefined) return null;

  if (!report) {
    return (
      <div className="mx-auto w-full max-w-3xl flex-1 px-5 py-16 text-center">
        <p className="text-foreground-muted">
          {lang === "en" ? "Report not found on this device." : "Informe no encontrado en este dispositivo."}
        </p>
        <Link href="/reports" className="mt-4 inline-block text-accent underline">
          {strings.nav.reports}
        </Link>
      </div>
    );
  }

  const trustValues = report.trustHistory.map((h) => h.trustScore);
  const color = bandColor[report.finalBand];

  return (
    <div className="mx-auto w-full max-w-4xl flex-1 px-5 py-10 print:max-w-full">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="text-xs uppercase tracking-wide text-foreground-muted">{strings.report.title}</div>
          <h1 className="mt-1 text-2xl font-semibold tracking-tight">{report.scenario}</h1>
          <div className="mt-1 text-sm text-foreground-muted">
            {new Date(report.startedAt).toLocaleString(lang === "en" ? "en-US" : "es-ES")} ·{" "}
            {Math.round(report.durationMs / 1000)}s
          </div>
        </div>
        <div className="flex flex-wrap gap-2 print:hidden">
          <button
            onClick={async () => {
              try {
                await navigator.clipboard.writeText(buildFtcStyleReport(report, lang));
                showToast(lang === "en" ? "Summary copied to clipboard" : "Resumen copiado al portapapeles", "success");
              } catch {
                showToast(lang === "en" ? "Couldn't copy — try the download instead" : "No se pudo copiar — intenta la descarga", "danger");
              }
            }}
            className="btn-press rounded-full border border-border-strong px-4 py-2 text-xs font-medium hover:bg-background-elevated"
          >
            {lang === "en" ? "Copy summary" : "Copiar resumen"}
          </button>
          <button
            onClick={() => window.print()}
            className="btn-press rounded-full border border-border-strong px-4 py-2 text-xs font-medium hover:bg-background-elevated"
          >
            {strings.report.export}
          </button>
          <button
            onClick={() => {
              downloadFile(`guardian-line-report-${report.id}.txt`, buildFtcStyleReport(report, lang));
              showToast(lang === "en" ? "Report downloaded" : "Informe descargado", "success");
            }}
            className="btn-press rounded-full bg-accent-solid px-4 py-2 text-xs font-medium text-white hover:bg-accent-solid-hover"
          >
            {strings.report.fileScam}
          </button>
        </div>
      </div>

      <div className="card-hover animate-fade-in-up mt-8 grid grid-cols-1 sm:grid-cols-[auto_1fr] gap-6 rounded-2xl border border-border-subtle bg-background-card p-6">
        <div className="flex flex-col items-center justify-center">
          <div className="text-4xl font-bold tabular-nums" style={{ color }}>
            {report.finalTrustScore}
          </div>
          <div
            className="mt-2 rounded-full px-3 py-1 text-xs font-semibold"
            style={{ color, backgroundColor: `color-mix(in srgb, ${color} 16%, transparent)` }}
          >
            {bandLabel[lang][report.finalBand]}
          </div>
        </div>
        <div>
          <div className="text-xs text-foreground-muted mb-2">
            {lang === "en" ? "Trust score over time" : "Puntuación de confianza en el tiempo"}
          </div>
          {trustValues.length > 1 ? (
            <svg viewBox="0 0 300 60" className="w-full h-16" preserveAspectRatio="none">
              <path d={sparklinePath(trustValues, 300, 60)} fill="none" stroke={color} strokeWidth={2} />
            </svg>
          ) : (
            <div className="text-xs text-foreground-muted">
              {lang === "en" ? "Not enough data captured." : "No se capturaron suficientes datos."}
            </div>
          )}
          {report.safeWordChallenged && (
            <div className="mt-3 flex items-center gap-2 text-xs">
              <KeyIcon className="h-4 w-4 text-accent" />
              {report.safeWordPassed ? (
                <span className="text-trust-safe flex items-center gap-1">
                  <CheckIcon className="h-3.5 w-3.5" /> {strings.safeWord.passed}
                </span>
              ) : (
                <span className="text-trust-danger">{strings.safeWord.failed}</span>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="mt-6 grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="card-hover animate-fade-in-up rounded-2xl border border-border-subtle bg-background-card p-5 h-[420px]" style={{ animationDelay: "80ms" }}>
          <h2 className="mb-3 text-sm font-semibold text-foreground-muted">
            {lang === "en" ? "Full transcript" : "Transcripción completa"}
          </h2>
          <div className="h-[calc(100%-2rem)]">
            <TranscriptView entries={report.transcript} />
          </div>
        </div>
        <div className="card-hover animate-fade-in-up rounded-2xl border border-border-subtle bg-background-card p-5 h-[420px]" style={{ animationDelay: "140ms" }}>
          <h2 className="mb-3 text-sm font-semibold text-foreground-muted">
            {lang === "en" ? "Flagged moments" : "Momentos marcados"}
          </h2>
          <div className="h-[calc(100%-2rem)]">
            <ExplainabilityPanel flags={report.flags} />
          </div>
        </div>
      </div>
    </div>
  );
}
